server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: auth-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**
          filters:
            - RemoveRequestHeader=Cookie

        - id: customer-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/customers/**
          filters:
            - name: CircuitBreaker
              args:
                name: customerCircuitBreaker
                fallbackUri: forward:/fallback/customers

        - id: loan-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/loans/**
          filters:
            - name: CircuitBreaker
              args:
                name: loanCircuitBreaker
                fallbackUri: forward:/fallback/loans

        - id: document-notification-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/documents/**, /api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationCircuitBreaker
                fallbackUri: forward:/fallback/notifications
            - RemoveRequestHeader=Transfer-Encoding
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: 10MB

auth:
  public-key-url: http://localhost:8080/api/auth/public-key

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      loanCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      customerCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
      notificationCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50

management:
  tracing:
    enabled: false

logging:
  level:
    root: INFO
    com.bank.loan: DEBUG
